spring:
  datasource:
    username: utczdzuqtqvspx
    password: f58683d2216d53074944a187e4e3b4ea3044b6202d6e16272ecb248d8109f3cb
    url: postgres://utczdzuqtqvspx:f58683d2216d53074944a187e4e3b4ea3044b6202d6e16272ecb248d8109f3cb@ec2-52-208-145-55.eu-west-1.compute.amazonaws.com:5432/debu6cf4g237t6
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        time_zone: UTC
    show-sql: true # Set true for debugging
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # (create, create-drop, validate, update)

    open-in-view: false
  sql:
    init:
      platform: postgres
      mode: always


